version: '3'
services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "5001:5001"
  user_service:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "5002:5002"
  notification_service:
    build:
      context: .
      dockerfile: Dockerfile.notification
    ports:
      - "5003:5003"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices
    ports:
      - "5432:5432"